Rails/NotesApp/config/routes.rb
Rails.application.routes.draw do
	get 'omniauth_callbacks/facebook'

  devise_for :users, skip: [:registrations], controllers: {
    omniauth_callbacks: "omniauth_callbacks"
  }
  authenticated :user do
	  root 'notes#index', as: :authenticated_root
	  resources :notes
  	resources :categories
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

Rails/NotesApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Rails/NotesApp/app/models/category.rb
class Category < ApplicationRecord
	has_many :notes
end

Rails/NotesApp/app/models/note.rb
class Note < ApplicationRecord
  belongs_to :category
  belongs_to :user

  validates :title, presence: true, uniqueness: true
	validates :body, presence: true, length: { minimum: 10 }

  before_save :set_visits_count

  def self.search(search)
  	if search
  		Note.where("title LIKE ? or body LIKE ?", "%#{search}%", "%#{search}%")
  	else
  		Note.all
  	end
  end

  def update_visits_count
		self.save if self.num_views.nil?
		self.update(num_views: self.num_views + 1)
	end

	private
	def set_visits_count
		self.num_views ||= 0
	end

end

Rails/NotesApp/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable,
         :omniauth_providers => [:facebook]

  has_many :notes

  def self.from_omniauth(auth)
  	where(provider: auth["provider"], uid: auth["uid"]).first_or_create do |user|
  		if auth[:info]
  			user.email = if auth[:info][:email].nil? || auth[:info][:email].empty? then "#{auth[:info][:name].split(" ").join("")}@gmail.com" else auth[:info][:email] end
  			user.name = auth[:info][:name]
        user.last_name = auth[:info][:last_name]
        user.image = auth[:info][:image]
  		end
  		user.password = Devise.friendly_token[0,20]
  	end
  end
end

Rails/NotesApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
end

Rails/NotesApp/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @notes = @category.notes
    render "notes/index"
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :image)
    end
end

Rails/NotesApp/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	render :layout => "layouts/_register"
  end
end

Rails/NotesApp/app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    if params[:m]=="1"
      @notes = current_user.notes
      @title = "Mis notas"
      return
    end
    @notes = Note.search(params[:search])
    #raise @notes.inspect.to_yaml
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
    @note.update_visits_count
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = current_user.notes.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Se creo la nota satisfactoriamente.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.user_id === current_user.id && @note.update(note_params)
        format.html { redirect_to @note, notice: 'Nota actualizada correctamente.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { redirect_to edit_note_path(@note.id), alert: "Usted no puede actualizar la nota." }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    if @note.user_id === current_user.id
      @note.destroy
      @message = "La Nota se elimino con éxito."
    else
      @message = "Error al eliminar, usted no es el dueño de la nota."
    end
    respond_to do |format|
      format.html { redirect_to notes_url, notice: @message }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:title, :body, :category_id, :flag)
    end
end

Rails/NotesApp/app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < ApplicationController
	#skip_before_action :authenticate_user!, only: [:facebook, :custom_sign_up]
  def facebook
		@user = User.from_omniauth(request.env["omniauth.auth"])

		if @user.persisted?
			@user.remember_me = true
			sign_in_and_redirect @user, event: :authentication
			return
		end

		session["devise.auth"] = request.env["omniauth.auth"]

		render :edit

	end

  def failure
	  redirect_to root_path, notice: "Error: #{params[:error_description]}. Motivo: #{params[:error_reason]}"
	end

	private

	def user_params
	  params.require(:user).permit(:name, :last_name,	:email)
	end
end

Rails/NotesApp/app/helpers/application_helper.rb
module ApplicationHelper
end

Rails/NotesApp/app/helpers/categories_helper.rb
module CategoriesHelper
end

Rails/NotesApp/app/helpers/home_helper.rb
module HomeHelper
end

Rails/NotesApp/app/helpers/notes_helper.rb
module NotesHelper
end

Rails/NotesApp/app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

Rails/NotesApp/app/views/categories/_form.html.erb
<%= form_for(category) do |f| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.text_field :image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Rails/NotesApp/app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

Rails/NotesApp/app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>
  <div class="row">
    <% @categories.each do |category| %>
      <div class="col s12 m3">
        <div class="card" style="height: 300px; max-height: 300px;">
          <div class="card-image">
            <img src=<%="#{category.image}" %>>
            <%= link_to category_path(category), class: "btn-floating halfway-fab waves-effect waves-light green" do %>
              <i class="material-icons">search</i>
            <% end %>
          </div>
          <div class="card-content">
            <span class="card-title blue-text"><%= category.name %></span>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="divider"></div>
  <%= link_to notes_path, class: "btn waves-effect waves-light" do %>
    <i class="material-icons right">send</i>Atras
  <% end %>

Rails/NotesApp/app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

Rails/NotesApp/app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

Rails/NotesApp/app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<%= link_to "Registrate", user_facebook_omniauth_authorize_path %>

Rails/NotesApp/app/views/layouts/_register.html.erb
<!DOCTYPE html>
<html class="indigo lighten-3 fondo">
  <head>
    <meta charset="utf-8">
    <title>Free Notes</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="row fondo" style="margin-top:65px;">
      <div class="col s3 m3 l4">
      </div>
      <div class="col s6 m6 l4">
        <% unless notice.nil? %>
          <div class="row">
            <div class="col s12 m10 l10 offset-m1 offset-l1">
              <div class="chip red" style="padding: 10px 10px 10px 10px; width: 100%; height: 50px;">
                <i class="material-icons white-text left" style="padding-top: 2px;">report_problem</i>
                <h6 class="white-text"><b>OOPS!</b> <%= notice %>: <%= alert %><h6>
              </div>
            </div>
          </div>
        <% end %>

        <div class="card teal lighten-2">

          <div class="card-image" style="">
            <%= image_tag "image.png" %>
            <div class="right">
              <span class="card-title purple-text edarken-4 title">Note Free</span>
            </div>            
          </div>
          <div class="card-content">
            <p>¿No quieres olvidar algo?, ¿perdiste una cita? No todo esta perdido...</p>
            <h5 class="center">¡¡Que estas esperando!!</h5>
          </div>
          <div class="card-action center">
            <%= form_tag user_facebook_omniauth_authorize_path, method: :post do %>
              <%= button_tag 'Login with Facebook', class: "loginBtn loginBtn--facebook hoverable " %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col s3 m3 l4">
      </div>
    </div>
    <footer class="page-footer">
      <div class="footer-copyright center blue lighten-2">
        <div class="container">
          <p>© 2017 Copyright Text - By: <a href="https://www.facebook.com/andresfrankm"> Andres Frank Alexis </a></p>
        </div>
      </div>
    </footer>
  </body>
</html>

Rails/NotesApp/app/views/layouts/application.html.erb
<html class="indigo lighten-3">
  <head>
    <meta charset="utf-8">
    <% @title ||= "NoteApp" %>
    <title><%= @title%></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <div class="hide-on-large-only">
      <nav>
        <div class="nav-wrapper indigo lighten-1">
          <a href="" data-activates="slide-out" class="button-collapse top-nav waves-effect waves-light circle hide-on-large-only">
            <i class="material-icons">menu</i>
          </a>
          <a href="" class="brand-logo center">
            <h4 class="center-on-small-only center-align"><%= @title%></h4>
            <!--<img class="responsive-img" src=<%= image_url('logo.jpg') %>>-->
          </a>
        </div>
      </nav>
    </div>

    <ul id="slide-out" class="side-nav indigo lighten-1 center">
      <li>
        <div class="userView">
          <div class="background">
            <li style="padding-top: 5px;"><%= image_tag current_user.image, class: "circle responsive-img" %></li>
          </div>
          <a href=""><span class="name white-text"><%= current_user.name %></span></a>
          <a href=""><span class="email white-text"><%= current_user.email %></span></a>
        </div>
      </li>
      <li><div class="divider"></div></li>
      <li>
        <%= form_tag notes_path, :method => 'get' do %>
          <div class="input-field">
            <%= text_field_tag :search, params[:search], class: "validate", id: "search", required: true %>
            <label class="label-icon" for="search"><i class="material-icons">search</i></label>
          </div>
        <% end %>
      </li>
      <li><%= link_to "Mis Notas", notes_path(m: 1), class: "waves-effect white-text" %></li>
      <li><%= link_to "Todas las Notas", notes_path, class: "waves-effect white-text" %></li>
      <li><%= link_to "Categorias", categories_path, class: "waves-effect white-text" %></li>

      <li><div class="divider"></div></li>
      <li>
        <%= link_to destroy_user_session_path, class:"white-text", :method => :delete do %>
          <i class="material-icons right">settings_power</i>Cerrar Sesión
        <% end %>
      </li>
              
    </ul>

    <header>
      <div class="hide-on-med-and-down">
        <nav>
          <div class="nav-wrapper">
            <a href="#!" class="brand-logo">
              <%= image_tag "favicon.png", class: "circle responsive-img" %>
            </a>
            <ul class="right">
              <li>
                <%= form_tag notes_path, :method => 'get' do %>
                  <div class="input-field">
                    <%= text_field_tag :search, params[:search], class: "validate", id: "search", required: true %>
                    <label class="label-icon" for="search"><i class="material-icons">search</i></label>
                  </div>
                <% end %>
              </li>
              <li><%= link_to "Mis Notas", notes_path(m: 1), class: "waves-effect" %></li>
              <li><%= link_to "Todas las Notas", notes_path, class: "waves-effect" %></li>
              <li><%= link_to "Categorias", categories_path, class: "waves-effect" %></li>
              <li style="padding-top: 5px;"><%= image_tag current_user.image, class: "circle responsive-img" %></li>
              <li>
                <%= link_to destroy_user_session_path, :method => :delete do %>
                  <i class="material-icons">settings_power</i>
                <% end %>
              </li>
            </ul>
          </div>
        </nav>
      </div>
    </header>
    <main>
      <div class="container">
        <% if !notice.nil? %>
          <div class="card-panel green">
            <span class="white-text">
              <span class="notice"><%= notice %></span>
            </span>
          </div>
        <% end %>
        <% if !alert.nil? %>
          <div class="card-panel red">
            <span class="white-text">
              <span class="alert"><%= alert %></span>
            </span>
          </div>
        <% end %>
        <br />  
        <%= yield %>
      </div>
    </main>
  </body>
</html>

Rails/NotesApp/app/views/notes/_form.html.erb
<%= form_for note, html: {class: "col s12"} do |f| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="input-field col s12">
      <%= f.label "Titulo", for: "Titulo" %>
      <%= f.text_field :title, id: "Titulo" %>
    </div>

    <div class="input-field col s12">
      <%= f.label "Texto", for: "body" %>
      <%= f.text_area :body, id: "body", class: "materialize-textarea" %>
    </div>

    <div class="col s3"></div>
    <div class="field col s6">
      <%= f.label "Categoria", style: "color: #1B5E20" %>
      <%= f.select(:category_id, options_from_collection_for_select(Category.all, :id, :name), {:prompt => 'Seleccione una categoria'}, :class => "") %>
    </div>
    <div class="col s3"></div>

    <div class="col s4"></div>
    <div class="field col s4">
      <%= f.check_box :flag, id: "Importante" %>
      <%= f.label :flag, 'Importante', for: "Importante", style: "color: #1B5E20" %>
    </div>
    <div class="col s4"></div>

    <div class="input-field col s12">
      <button class="btn waves-effect waves-light" type="submit" name="action">Enviar
        <i class="material-icons right">send</i>
      </button>
    </div>
    
  </div>
<% end %>

Rails/NotesApp/app/views/notes/edit.html.erb
<% @title = "Editando...."%>
<div class="container center">
	<div class="row">
		<div class="col s2 m2">.</div>
    <div class="col s10 m8 l8 center teal lighten-2 z-depth-4">
    	<h3>Editar Nota</h3>
			<%= render 'form', note: @note %>
    </div>
    <div class="col s2 m2">.</div>
  </div>
  <%= link_to @note, class: "btn waves-effect waves-light" do %>
		<i class="material-icons right">send</i>Ver Nota
	<% end %>
	<%= link_to notes_path, class: "btn waves-effect waves-light" do %>
		<i class="material-icons right">send</i>Atras
	<% end %>
</div>

Rails/NotesApp/app/views/notes/index.html.erb
<div class="row">
  <div class="col s12 center">
    <% @title ||="Todas la Notas"%>

    <%= link_to new_note_path, class: "btn waves-effect waves-light red" do %>
      <i class="material-icons right">add</i>Agregar
    <% end %>

    <div class="row">
      <% if !@notes.nil? && @notes.count > 0%>
        <% @notes.each do |note| %>
          <div class="col m4 s6 l4">
            <div class="card blue-grey darken-1 hoverable" style="min-height: 300px;">
              <div class="card-content white-text">
                <span class="card-title truncate"><%= note.title %></span>
                <div class="divider"></div>
                <p class="truncate"><%= note.body %></p>
                <br />
                <p class="right-align">Por: <%= note.user.name %></p>
              </div>
              <div class="divider"></div>
              <div class="card-action blue-text darken-4">
                <div class="row" style="margin-bottom: 0px">
                  <div class="col s12 center">
                    <% if note.flag==true %>
                      <span>Importante</span>|
                    <% end %>
                    <span>Categoria: <%= note.category.name %></span>|
                    <span>Numero de Vistas: <%= note.num_views %></span>
                  </div>
                  <div class="col s12 right-align">
                    <% if note.flag==true %>
                      <a class="btn-floating btn-large waves-effect waves-light grey tooltipped" data-delay="50" data-tooltip="Importante"><i class="material-icons">warning</i></a>
                    <% end %>
                    <%= link_to note_path(note), class: "btn-floating btn-large waves-effect waves-light green" do %>
                      <i class="material-icons right">search</i>
                    <% end %>
                    <% if note.user_id == current_user.id %>
                      <%= link_to edit_note_path(note), class: "btn-floating btn-large waves-effect waves-light yellow" do %>
                        <i class="material-icons right">edit</i>
                      <% end %>
                      <%= link_to note, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn-floating btn-large waves-effect waves-light red" do %>
                        <i class="material-icons">delete</i>
                      <% end %>
                    <% end %>
                  </div>
                </div> 
              </div>
            </div>
          </div>
        <% end %>
      <% else %>
        <h3>No se encontraron Notas :(</h3>
      <% end %>
    </div>
  </div>
</div>

Rails/NotesApp/app/views/notes/new.html.erb
<% @title = "Agregando...."%>
<div class="container center">
	<div class="row center">
		<div class="col s2 m2">.</div>
    <div class="col s12 m8 l8 center teal lighten-2 z-depth-4">
    	<h3>Agregar Nota</h3>
			<%= render 'form', note: @note %>
    </div>
    <div class="col s2 m2">.</div>
  </div>
	<%= link_to notes_path, class: "btn waves-effect waves-light" do %>
		<i class="material-icons right">send</i>Atras
	<% end %>
</div>

Rails/NotesApp/app/views/notes/show.html.erb
<div class="row">
  <div class="col s12 m2">.</div>
  <div class="col s12 m8 center">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <span class="card-title"><%= @note.title %></span>
        <p><%= @note.body %></p>
        <br />
        <p class="right-align">Por: <%= @note.user.name %></p>
      </div>
      <div class="card-action white-text">
        <div class="row" style="margin-bottom: 0px">
          <div class="col s8 m9 center">
            <% if @note.flag==true %>
              <span>Importante</span>|
            <% end %>
            <span>Categoria: <%= @note.category.name %></span>|
            <span>Numero de Vistas: <%= @note.num_views %></span>
          </div>
          <div class="col s4 m3">
            <% if @note.user_id == current_user.id %>
              <%= link_to edit_note_path(@note), class: "btn-floating btn-large waves-effect waves-light yellow" do %>
                <i class="material-icons right">edit</i>
              <% end %>
              <%= link_to @note, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn-floating btn-large waves-effect waves-light red" do %>
                <i class="material-icons">delete</i>
              <% end %>
            <% end %>
          </div>
        </div>      
      </div>
    </div>
    <%= link_to notes_path, class: "btn waves-effect waves-light" do %>
      <i class="material-icons right">send</i>Atras
    <% end %>
  </div>
  <div class="col s12 m2">.</div>
</div>